FROM node:14.19.0-alpine
WORKDIR /app/
COPY package*.json ./
COPY ./docker/docker-entrypoint.local.sh /docker-entrypoint.local.sh
RUN chmod +x /docker-entrypoint.local.sh
ENTRYPOINT /docker-entrypoint.local.sh